# Generated by Django 2.2.1 on 2019-06-03 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTeam',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, default='', max_length=50)),
                ('team_captain', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LabUserteachaer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(blank=True, default='', max_length=20)),
                ('teacher_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('teacher_introduction', models.TextField(blank=True, null=True)),
                ('teacher_access', models.IntegerField(default='1')),
                ('teacher_postion', models.CharField(blank=True, default='', max_length=20)),
                ('belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LabUserteachaer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabUserstudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, default='', max_length=20)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('student_introduction', models.TextField(blank=True, null=True)),
                ('student_major', models.CharField(blank=True, default='', max_length=20)),
                ('student_access', models.IntegerField(default='2')),
                ('belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LabUserstudent', to=settings.AUTH_USER_MODEL)),
                ('student_teamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabTeam')),
            ],
        ),
        migrations.CreateModel(
            name='LabUsercommen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commen_account', models.IntegerField(default='')),
                ('commen_name', models.CharField(blank=True, default='', max_length=20)),
                ('commen_major', models.CharField(blank=True, default='', max_length=20)),
                ('commen_number', models.IntegerField()),
                ('belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LabUsercommen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
