# Generated by Django 2.2.1 on 2019-06-04 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabUserteacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(blank=True, default='', max_length=20)),
                ('teacher_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('teacher_introduction', models.TextField(blank=True, null=True)),
                ('teacher_access', models.IntegerField(default='1')),
                ('teacher_postion', models.CharField(blank=True, default='', max_length=20)),
                ('belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LabUserteacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LabUserteachaer',
        ),
    ]
