# Generated by Django 2.2.1 on 2019-06-04 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190604_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labgain',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabUserstudent'),
        ),
        migrations.AlterField(
            model_name='labuserteacher',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LabUserteacher', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
