# Generated by Django 2.2.1 on 2019-06-04 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190604_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labgain',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabUserstudent', to_field='student_name'),
        ),
    ]
