# Generated by Django 2.2.1 on 2019-06-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190604_0315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabGain',
        ),
    ]
