# Generated by Django 2.2.1 on 2019-06-04 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_labgain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labgain',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabUserstudent'),
        ),
    ]
