# Generated by Django 2.2.1 on 2019-06-04 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190604_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to=None)),
                ('date_time', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabUserstudent')),
            ],
        ),
    ]
