# Generated by Django 2.2.1 on 2019-06-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_labregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labregister',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
