# Generated by Django 2.2.1 on 2019-06-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190604_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_plan', models.CharField(blank=True, default='', max_length=20)),
                ('user_plandate', models.DateField()),
                ('user_remind', models.BooleanField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='LabsPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_ID', models.ForeignKey(on_delete='CASCADE', to='api.LabPlan')),
                ('user_ID', models.ForeignKey(on_delete='CASCADE', to='api.LabUserstudent')),
            ],
        ),
    ]
