# Generated by Django 2.2.1 on 2019-06-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_labplan_labsplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabsPlan',
        ),
    ]
