# Generated by Django 2.2.1 on 2019-06-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_labcompete_labcompeteteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPraProb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_difficult', models.IntegerField()),
                ('prob_body', models.TextField(max_length=2048)),
                ('prob_option_a', models.CharField(max_length=1024)),
                ('prob_option_b', models.CharField(max_length=1024)),
                ('prob_option_c', models.CharField(max_length=1024)),
                ('prob_option_d', models.CharField(max_length=1024)),
                ('prob_right', models.CharField(max_length=50, null=True)),
                ('prob_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LabPracResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prac_score', models.IntegerField()),
                ('prac_ratio', models.FloatField(max_length=64)),
                ('prac_difcult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabPraProb')),
                ('prac_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabUserstudent')),
            ],
        ),
    ]
