# Generated by Django 2.2.1 on 2019-06-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190604_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpraprob',
            name='prob_difficult',
            field=models.IntegerField(default='1'),
        ),
    ]
