# Generated by Django 2.2.1 on 2019-06-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190604_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPraProb2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_difficult', models.IntegerField(default='2')),
                ('prob_body', models.TextField(max_length=2048)),
                ('prob_option_a', models.CharField(max_length=1024)),
                ('prob_option_b', models.CharField(max_length=1024)),
                ('prob_option_c', models.CharField(max_length=1024)),
                ('prob_option_d', models.CharField(max_length=1024)),
                ('prob_right', models.CharField(max_length=50, null=True)),
                ('prob_score', models.IntegerField(default='4')),
            ],
        ),
        migrations.CreateModel(
            name='LabPraProb3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_difficult', models.IntegerField(default='3')),
                ('prob_body', models.TextField(max_length=2048)),
                ('prob_option_a', models.CharField(max_length=1024)),
                ('prob_option_b', models.CharField(max_length=1024)),
                ('prob_option_c', models.CharField(max_length=1024)),
                ('prob_option_d', models.CharField(max_length=1024)),
                ('prob_right', models.CharField(max_length=50, null=True)),
                ('prob_score', models.IntegerField(default='5')),
            ],
        ),
        migrations.RenameModel(
            old_name='LabPraProb',
            new_name='LabPraProb1',
        ),
        migrations.DeleteModel(
            name='LabPracResult',
        ),
    ]
