# Generated by Django 2.2.1 on 2019-06-05 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_labprapaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPracResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prac_score', models.IntegerField()),
                ('prac_ratio', models.FloatField(default='%0', max_length=64)),
                ('prac_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabPraPaper')),
                ('prac_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabUserstudent')),
            ],
        ),
    ]
