# Generated by Django 2.2.1 on 2019-06-05 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_labpracresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labprapaper',
            name='paper_d1',
        ),
        migrations.DeleteModel(
            name='LabPraProb1',
        ),
    ]
