# Generated by Django 2.2.1 on 2019-06-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190605_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPraProb1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_difficult', models.IntegerField(default='1')),
                ('prob_body', models.TextField(max_length=2048, null=True)),
                ('prob_option_a', models.CharField(max_length=1024, null=True)),
                ('prob_option_b', models.CharField(max_length=1024, null=True)),
                ('prob_option_c', models.CharField(max_length=1024, null=True)),
                ('prob_option_d', models.CharField(max_length=1024, null=True)),
                ('prob_right', models.CharField(max_length=50, null=True)),
                ('prob_score', models.IntegerField(default='2')),
            ],
        ),
        migrations.RemoveField(
            model_name='labprapaper',
            name='paper_d2',
        ),
        migrations.RemoveField(
            model_name='labprapaper',
            name='paper_d3',
        ),
        migrations.DeleteModel(
            name='LabPracResult',
        ),
        migrations.DeleteModel(
            name='LabPraPaper',
        ),
    ]
