# Generated by Django 2.2.1 on 2019-06-05 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190605_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPraPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_difficult', models.IntegerField(default='1')),
                ('paper_d1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabPraProb1')),
                ('paper_d2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabPraProb2')),
                ('paper_d3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabPraProb3')),
            ],
        ),
        migrations.CreateModel(
            name='LabPracResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prac_score', models.IntegerField()),
                ('prac_ratio', models.FloatField(default='%0', max_length=64)),
                ('prac_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabPraPaper')),
                ('prac_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabUserstudent')),
            ],
        ),
    ]
