# Generated by Django 2.2.1 on 2019-06-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_labpracresult_labprapaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labprapaper',
            name='paper_d1',
        ),
        migrations.AddField(
            model_name='labprapaper',
            name='paper_d1',
            field=models.ManyToManyField(to='api.LabPraProb1'),
        ),
        migrations.RemoveField(
            model_name='labprapaper',
            name='paper_d2',
        ),
        migrations.AddField(
            model_name='labprapaper',
            name='paper_d2',
            field=models.ManyToManyField(to='api.LabPraProb2'),
        ),
        migrations.RemoveField(
            model_name='labprapaper',
            name='paper_d3',
        ),
        migrations.AddField(
            model_name='labprapaper',
            name='paper_d3',
            field=models.ManyToManyField(to='api.LabPraProb3'),
        ),
    ]
