# Generated by Django 2.2.1 on 2019-06-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190605_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPraProbt1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_difficult', models.IntegerField(default='1')),
                ('prob_body', models.TextField(max_length=2048, null=True)),
                ('prob_option_a', models.CharField(max_length=1024, null=True)),
                ('prob_option_b', models.CharField(max_length=1024, null=True)),
                ('prob_option_c', models.CharField(max_length=1024, null=True)),
                ('prob_option_d', models.CharField(max_length=1024, null=True)),
                ('prob_right', models.CharField(max_length=50, null=True)),
                ('prob_score', models.IntegerField(default='2')),
            ],
        ),
        migrations.CreateModel(
            name='LabPraProbt2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_difficult', models.IntegerField(default='2')),
                ('prob_body', models.TextField(max_length=2048)),
                ('prob_option_a', models.CharField(max_length=1024)),
                ('prob_option_b', models.CharField(max_length=1024)),
                ('prob_option_c', models.CharField(max_length=1024)),
                ('prob_option_d', models.CharField(max_length=1024)),
                ('prob_right', models.CharField(max_length=50, null=True)),
                ('prob_score', models.IntegerField(default='4')),
            ],
        ),
        migrations.CreateModel(
            name='LabPraProbt3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_difficult', models.IntegerField(default='3')),
                ('prob_body', models.TextField(max_length=2048)),
                ('prob_option_a', models.CharField(max_length=1024)),
                ('prob_option_b', models.CharField(max_length=1024)),
                ('prob_option_c', models.CharField(max_length=1024)),
                ('prob_option_d', models.CharField(max_length=1024)),
                ('prob_right', models.CharField(max_length=50, null=True)),
                ('prob_score', models.IntegerField(default='5')),
            ],
        ),
        migrations.AlterField(
            model_name='labprapaper',
            name='paper_d1',
            field=models.ManyToManyField(to='api.LabPraProbt1'),
        ),
        migrations.AlterField(
            model_name='labprapaper',
            name='paper_d2',
            field=models.ManyToManyField(to='api.LabPraProbt2'),
        ),
        migrations.AlterField(
            model_name='labprapaper',
            name='paper_d3',
            field=models.ManyToManyField(to='api.LabPraProbt3'),
        ),
    ]
