# Generated by Django 2.2.1 on 2019-06-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190610_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpraprobd2',
            name='prob_body',
            field=models.TextField(default='多选题的难度为2', max_length=2048),
        ),
        migrations.AlterField(
            model_name='labpraprobd2',
            name='prob_option_a',
            field=models.CharField(default='A', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobd2',
            name='prob_option_b',
            field=models.CharField(default='B', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobd2',
            name='prob_option_c',
            field=models.CharField(default='C', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobd2',
            name='prob_option_d',
            field=models.CharField(default='D', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobd2',
            name='prob_right',
            field=models.CharField(default='ABC', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labpraprobd3',
            name='prob_body',
            field=models.TextField(default='多选题的难度为3', max_length=2048),
        ),
        migrations.AlterField(
            model_name='labpraprobd3',
            name='prob_option_a',
            field=models.CharField(default='A', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobd3',
            name='prob_option_b',
            field=models.CharField(default='B', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobd3',
            name='prob_option_c',
            field=models.CharField(default='C', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobd3',
            name='prob_option_d',
            field=models.CharField(default='D', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobd3',
            name='prob_right',
            field=models.CharField(default='AD', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labpraprobk1',
            name='prob_body',
            field=models.TextField(default='填空题难度为1', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='labpraprobk2',
            name='prob_body',
            field=models.TextField(default='填空题难度为2', max_length=2048),
        ),
        migrations.AlterField(
            model_name='labpraprobk3',
            name='prob_body',
            field=models.TextField(default='填空题难度为3', max_length=2048),
        ),
        migrations.AlterField(
            model_name='labpraprobp1',
            name='prob_body',
            field=models.TextField(default='判断题难度为1', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='labpraprobp1',
            name='prob_option_a',
            field=models.CharField(default='A', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='labpraprobp1',
            name='prob_option_b',
            field=models.CharField(default='B', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='labpraprobp1',
            name='prob_option_c',
            field=models.CharField(default='C', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='labpraprobp1',
            name='prob_option_d',
            field=models.CharField(default='D', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='labpraprobp1',
            name='prob_right',
            field=models.CharField(default='A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labpraprobp2',
            name='prob_body',
            field=models.TextField(default='判断题难度为2', max_length=2048),
        ),
        migrations.AlterField(
            model_name='labpraprobp2',
            name='prob_option_a',
            field=models.CharField(default='A', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobp2',
            name='prob_option_b',
            field=models.CharField(default='B', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobp2',
            name='prob_option_c',
            field=models.CharField(default='C', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobp2',
            name='prob_option_d',
            field=models.CharField(default='D', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobp2',
            name='prob_right',
            field=models.CharField(default='B', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labpraprobp3',
            name='prob_body',
            field=models.TextField(default='判断题难度为3', max_length=2048),
        ),
        migrations.AlterField(
            model_name='labpraprobp3',
            name='prob_option_a',
            field=models.CharField(default='A', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobp3',
            name='prob_option_b',
            field=models.CharField(default='B', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobp3',
            name='prob_option_c',
            field=models.CharField(default='C', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobp3',
            name='prob_option_d',
            field=models.CharField(default='D', max_length=1024),
        ),
        migrations.AlterField(
            model_name='labpraprobp3',
            name='prob_right',
            field=models.CharField(default='C', max_length=50, null=True),
        ),
    ]
