# Generated by Django 2.2.1 on 2019-06-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190610_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labregister',
            options={'ordering': ['-date_time']},
        ),
    ]
