# Generated by Django 2.2.1 on 2019-06-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190610_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labcompete',
            options={'ordering': ['compete_date']},
        ),
    ]
