# Generated by Django 2.2.1 on 2019-06-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20190610_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='labgain',
            name='gain_date',
            field=models.DateField(null=True),
        ),
    ]
