# Generated by Django 2.2.1 on 2019-06-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_labgain_gain_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labgain',
            old_name='gain_date',
            new_name='gain_getdate',
        ),
    ]
