# Generated by Django 2.2.1 on 2019-06-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20190610_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labgain',
            options={'ordering': ['-gain_getdate']},
        ),
    ]
