# Generated by Django 2.2.1 on 2019-06-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20190610_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_url', models.URLField(blank=True, null=True)),
                ('collect_data', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabsCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.ForeignKey(on_delete='CASCADE', to='api.LabUserstudent')),
            ],
        ),
        migrations.CreateModel(
            name='LabInNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50)),
                ('news_content', models.TextField()),
                ('news_date', models.DateField()),
                ('news_see', models.IntegerField()),
                ('news_comment', models.TextField(max_length=1024)),
                ('news_captainid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabUserstudent')),
            ],
        ),
        migrations.CreateModel(
            name='LabInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_content', models.TextField(default='')),
                ('information_photo', models.ImageField(blank=True, null=True, upload_to=None)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LabUserstudent')),
            ],
        ),
        migrations.CreateModel(
            name='LabEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_content', models.TextField(default='')),
                ('email_state', models.BooleanField(default=False)),
                ('email_send', models.ForeignKey(on_delete='CASCADE', to='api.LabUserstudent')),
            ],
        ),
    ]
