# Generated by Django 2.2.1 on 2019-06-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_labcollect_labemail_labinformation_labinnews_labscollect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labinnews',
            name='news_see',
            field=models.IntegerField(null=True),
        ),
    ]
