# Generated by Django 2.2.1 on 2019-06-10 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0038_auto_20190610_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=17)),
            ],
        ),
        migrations.AlterModelOptions(
            name='labinnews',
            options={'ordering': ['-news_date']},
        ),
        migrations.CreateModel(
            name='LabPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='在此输入贴子标题', max_length=30)),
                ('content', models.TextField(default='在此输入贴子内容')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('edited_data', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('post_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.LabPostType')),
            ],
            options={
                'ordering': ['-created_data'],
            },
        ),
    ]
