from django.contrib import admin
from api.models import LabUserteacher,LabUserstudent,LabUsercommen,LabTeam,LabGain,LabRegister,LabPlan,LabTPlan,LabCompete,LabCompeteTeam,LabPraProb1,LabPraProb2,LabPraProb3,LabPraPaper,LabPracResult,LabPraProbD1,LabPraProbD2,LabPraProbD3,LabPraProbP1,LabPraProbP2,LabPraProbP3,LabPraProbK1,LabPraProbK2,LabPraProbK3,LabCollect,LabsCollect,LabInNews,LabInformation, LabEmail,LabPost,LabPostType

# Register your models here.
admin.site.register(LabUserteacher)
admin.site.register(LabUserstudent)
admin.site.register(LabUsercommen)
admin.site.register(LabTeam)
admin.site.register(LabGain)
admin.site.register(LabRegister)
admin.site.register(LabPlan)
admin.site.register(LabTPlan)
admin.site.register(LabCompete)
admin.site.register(LabCompeteTeam)
admin.site.register(LabPraProb1)
admin.site.register(LabPraProb2)
admin.site.register(LabPraProb3)
admin.site.register(LabPraPaper)
admin.site.register(LabPracResult)
admin.site.register(LabPraProbD1)
admin.site.register(LabPraProbD2)
admin.site.register(LabPraProbD3)
admin.site.register(LabPraProbP1)
admin.site.register(LabPraProbP2)
admin.site.register(LabPraProbP3)
admin.site.register(LabPraProbK1)
admin.site.register(LabPraProbK2)
admin.site.register(LabPraProbK3)
admin.site.register(LabCollect)
admin.site.register(LabsCollect)
admin.site.register(LabInNews)
admin.site.register(LabInformation)
admin.site.register(LabEmail)
admin.site.register(LabPost)
admin.site.register(LabPostType)